esphome:
  name: "aurmouse-test"
  libraries:
    - "ESP32 BLE Mouse"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Set up I2C for the MPU6050
i2c:
  sda: 8
  scl: 9
  scan: true

captive_portal:
logger:
  level: VERBOSE
api:
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: mpu6050
    address: 0x68
    accel_x:
      name: "Accel X"
    accel_y:
      name: "Accel Y"
    gyro_x:
      id: "gyro_x"
      name: "Gyro X"
    gyro_y:
      id: "gyro_y"
      name: "Gyro Y"
      # MOVE THE TRIGGER HERE
      on_value:
        then:
          - lambda: |-
              static BleMouse bleMouse("ESPHome AirMouse", "Google", 100);
              if (!bleMouse.isConnected()) {
                bleMouse.begin();
              } else {
                float sensitivity = 0.5;
                
                // We use the ID system to get BOTH values even though 
                // we are technically inside the gyro_y trigger.
                signed char mouse_x = (id(gyro_y).state) * sensitivity;
                signed char mouse_y = (id(gyro_x).state) * sensitivity;
                
                if (abs(mouse_x) > 1 || abs(mouse_y) > 1) {
                  bleMouse.move(mouse_x, mouse_y);
                }
              }
    update_interval: 20ms