esphome:
  name: "airmouse-test"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: custom_components

esp32_ble:

ble_mouse:
  id: my_mouse
  name: "ESPHome AirMouse"

# Set up I2C for the MPU6050
i2c:
  sda: 4
  scl: 5
  scan: true

captive_portal:
logger:
  level: VERBOSE
api:
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: mpu6050
    address: 0x68
    accel_x:
      name: "Accel X"
    accel_y:
      name: "Accel Y"
    gyro_x:
      id: "gyro_x"
      name: "Gyro X"
    gyro_y:
      id: "gyro_y"
      name: "Gyro Y"
      on_value:
        then:
          - ble_mouse.move:
              id: my_mouse
              x: !lambda |-
                float sensitivity = 0.5;
                return (int8_t)((id(gyro_y).state) * sensitivity);
              y: !lambda |-
                float sensitivity = 0.5;
                return (int8_t)((id(gyro_x).state) * sensitivity);
    update_interval: 20ms
