# Substitution variables used through the codebase
substitutions:
  <<: !include modules/base/mdi_glyph_substitutions.yaml
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"
  bed:               "\U000F02E3"
  mdi_monitor_multiple: "\U000F037A"
  mdi_monitor_small:    "\U000F1876"
  mdi_monitor:          "\U000F0379"

  bg_color: black
  icon_font: light40
  text_font: roboto24
  text_font_small: roboto18
  text_color: white
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '135px'
  button_height_double: '270px'
  button_width: '151px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  boot_screen_delay: 5s
  header_height: 20px
  footer_height: 30px
  screen_night_hour: '0'
  screen_night_minute: '0'
  screen_day_hour: '5'
  screen_day_minute: '30'
  screen_height: '480px'
  screen_width: '480px'
  sdl_height: '480'
  sdl_width: '480'

esphome:
  name: "desktop-dash"
  friendly_name: "desktop-dash"
  comment: "Sean Bedroom Desktop Dash"

api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: lbl_hastatus
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: lbl_hastatus

mqtt:
  broker: 192.168.1.99

time:
  - platform: sntp        
    id: sntp_time
    timezone: Australia/Melbourne
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time_sync:
      - script.execute: time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: display_time
          text: !lambda |-
            static char time_buf[17];
            auto now = id(sntp_time).now();            
            bool is_pm = now.hour >= 12;
            int hour_12 = now.hour % 12;
            if (hour_12 == 0) {
                hour_12 = 12; // 12 AM/PM should be displayed as 12, not 0
            }
            snprintf(time_buf, sizeof(time_buf), "%2d:%02d%s", hour_12, now.minute, is_pm ? "pm" : "am");
            return time_buf; 

packages:
  # Generic configuration for ESP32 screens
  wifi: !include 
    file: modules/base/wifi.yaml
    vars:
      use_address: 192.168.1.61
  base: !include modules/base/base.yaml
  touchscreen: !include modules/base/touchscreen.yaml
  backlight: !include modules/base/backlignt.yaml
  colors: !include modules/base/color.yaml
  fonts: !include modules/base/fonts.yaml
  images: !include modules/base/images.yaml
  sensors: !include modules/sensors/sensors_base.yaml
  theme_style: !include modules/base/theme_style.yaml
  hardware: !include modules/hardware/guition-esp32-s3-4848s040.yaml

  btn_sean_cover_office: !include
    file: modules/sensors/cover_state.yaml
    vars:
      uid: btn_sean_cover_office
      entity_id: cover.sean_s_office_blind

  btn_sean_cover_blinds: !include
    file: modules/sensors/cover_state.yaml
    vars:
      uid: btn_sean_cover_blinds
      entity_id: cover.sean_s_office_blind

  btn_living_cover_blinds: !include
    file: modules/sensors/cover_state.yaml
    vars:
      uid: btn_living_cover_blinds
      entity_id: cover.living_room_blind

  btn_master_cover_blinds: !include
    file: modules/sensors/cover_state.yaml
    vars:
      uid: btn_master_cover_blinds
      entity_id: cover.master_bedroom_blind

# LVGL pages and buttons
lvgl:
  top_layer: !include
    file: modules/screens/header_footer.yaml
    vars:
      height: $screen_height
      width: $screen_width
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN
      styles: page_style
      width: $screen_width
      bg_color: $bg_color
      bg_opa: cover
      widgets:
        - obj: !include
            file: modules/screens/header_title_object.yaml
            vars:
              title: Office
        - obj:
            width: 100%
            height: 70px
            align: CENTER
            layout:
              type: flex
              flex_flow: ROW_WRAP
              flex_align_main: CENTER
              flex_align_cross: CENTER
            widgets:
              - button: !include
                  file: modules/buttons/cover_blind_slider.yaml
                  vars:
                    uid: btn_sean_cover_office
                    width: 100%
                    height: 70px # Single height for bar
                    text: Blinds
                    icon: $mdi_blinds
                    entity_id: cover.sean_s_office_blind
        - obj:
            width: 100%
            height: $button_height_single
            align: CENTER
            layout:
              type: flex
              flex_flow: ROW_WRAP
              flex_align_main: CENTER
              flex_align_cross: CENTER
            widgets:
              - button:
                  id: switch_to_pc
                  height: $button_height_single
                  widgets:
                    - label:
                        id: switch_to_pc_label
                        align: CENTER
                        text: $mdi_desktop_tower
                        text_font: $icon_font
                    - label:
                        align: bottom_mid
                        id: switch_to_pc_text_label
                        text: "PC"
                  on_press:
                    - homeassistant.service:
                        service: button.press
                        data:
                          entity_id: button.9800x3d_displayultrawideonly
                    - mqtt.publish:
                        topic: monitor/input
                        payload: "pc"
              - button:
                  id: switch_to_mac
                  height: $button_height_single
                  widgets:
                    - label:
                        id: switch_to_mac_label
                        align: CENTER
                        text: $mdi_laptop
                        text_font: $icon_font
                    - label:
                        align: bottom_mid
                        id: switch_to_mac_text_label
                        text: "Mac"
                  on_press:
                    - mqtt.publish:
                        topic: monitor/input
                        payload: "mac"
                    - homeassistant.service:
                        service: button.press
                        data:
                          entity_id: button.9800x3d_displayoledonly
        - obj:
            align: CENTER
            styles: header_footer
            outline_width: 0
            id: label_pc_monitor_mode
            width: 100%
            height: $header_height
            widgets:
              - label:
                  text: "PC Monitor"
                  align: CENTER
                  text_align: CENTER
                  text_color: 0xFFFFFF
        - obj:
            width: 100%
            height: $button_height_single
            align: CENTER
            layout:
              type: flex
              flex_flow: ROW_WRAP
              flex_align_main: CENTER
              flex_align_cross: CENTER
            widgets:
              - button:
                  id: switch_to_dualscreen
                  height: $button_height_single
                  widgets:
                    - label:
                        id: switch_to_dualscreen_label
                        align: CENTER
                        text: $mdi_monitor_multiple
                        text_font: $icon_font
                    - label:
                        align: bottom_mid
                        id: switch_to_dualscreen_text_label
                        text: "Dual Screen"
                        text_font: $text_font_small
                  on_press:
                    - homeassistant.service:
                        service: button.press
                        data:
                          entity_id: button.9800x3d_displaydualscreen
              - button:
                  id: switch_to_oled
                  height: $button_height_single
                  widgets:
                    - label:
                        id: switch_to_oled_label
                        align: CENTER
                        text: $mdi_monitor_small
                        text_font: $icon_font
                    - label:
                        align: bottom_mid
                        id: switch_to_oled_text_label
                        text: "OLED Only"
                        text_font: $text_font_small
                  on_press:
                    - homeassistant.service:
                        service: button.press
                        data:
                          entity_id: button.9800x3d_displayoledonly
              - button:
                  id: switch_to_ultrawide
                  height: $button_height_single
                  widgets:
                    - label:
                        id: switch_to_ultrawide_label
                        align: CENTER
                        text: $mdi_monitor
                        text_font: $icon_font
                    - label:
                        align: bottom_mid
                        id: switch_to_ultrawide_text_label
                        text: "Ultrawide Only"
                        text_font: $text_font_small
                  on_press:
                    - homeassistant.service:
                        service: button.press
                        data:
                          entity_id: button.9800x3d_displayultrawideonly
    - id: blinds_page
      layout:
        type: flex
        flex_flow: ROW_WRAP
        flex_align_cross: CENTER
        flex_align_main: CENTER
      styles: page_style
      width: $screen_width
      bg_color: $bg_color
      bg_opa: cover
      widgets:
        - obj: !include
            file: modules/screens/header_title_object.yaml
            vars:
              title: Blinds
        - button: !include
            file: modules/buttons/cover_blind_button.yaml
            vars:
              uid: btn_sean_cover_blinds
              height: $button_height_double
              text: Office
              icon: $mdi_blinds
              entity_id: cover.sean_s_office_blind
        - button: !include
            file: modules/buttons/cover_blind_button.yaml
            vars:
              uid: btn_living_cover_blinds
              height: $button_height_double
              text: Living
              icon: $mdi_blinds
              entity_id: cover.living_room_blind
        - button: !include
            file: modules/buttons/cover_blind_button.yaml
            vars:
              uid: btn_master_cover_blinds
              height: $button_height_double
              text: Master
              icon: $mdi_blinds
              entity_id: cover.master_bedroom_blind
        - button:
            id: open_all_blinds
            height: $button_height_single
            widgets:
              - label:
                  id: open_all_blinds_label
                  align: CENTER
                  text: $mdi_blinds_open
                  text_font: $icon_font
              - label:
                  align: bottom_mid
                  id: open_all_blinds_text_label
                  text: "Open All"
            on_press:
              - homeassistant.action:
                  action: cover.open_cover
                  data:
                    entity_id: cover.master_bedroom_blind
              - homeassistant.action:
                  action: cover.open_cover
                  data:
                    entity_id: cover.living_room_blind
              - homeassistant.action:
                  action: cover.open_cover
                  data:
                    entity_id: cover.sean_s_office_blind
        - button:
            id: close_all_blinds
            height: $button_height_single
            widgets:
              - label:
                  id: close_all_blinds_label
                  align: CENTER
                  text: $mdi_blinds
                  text_font: $icon_font
              - label:
                  align: bottom_mid
                  id: close_all_blinds_text_label
                  text: "Close All"
            on_press:
              - homeassistant.action:
                  action: cover.close_cover
                  data:
                    entity_id: cover.master_bedroom_blind
              - homeassistant.action:
                  action: cover.close_cover
                  data:
                    entity_id: cover.living_room_blind
              - homeassistant.action:
                  action: cover.close_cover
                  data:
                    entity_id: cover.sean_s_office_blind
    - id: about_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      styles: page_style
      width: 100%
      bg_color: $bg_color
      bg_opa: cover
      widgets:
        - obj: !include
            file: modules/screens/header_title_object.yaml
            vars:
              title: About
        - image:
            src: boot_logo_90px
            pad_bottom: 10
        - label:
            id: esphome_version_label
            text:
              format: "ESPHome Version: %s"
              args: [ 'id(esphome_version).state.c_str()' ]
        - label:
            text:
              format: "Build Date: %s - %s"
              args: [__DATE__, __TIME__]
        - label:
            id: connected_mac_label
            text: "MAC Address: Not Connected"
        - label:
            id: ip_address_label
            text: "IP Address: Not Connected"
        - label:
            id: connected_ssid_label
            text: "Connected SSID: Not Connected"
        - label:
            id: wifi_signal_db_percent_label
            text: "WiFi Strength: Not Connected"
        - button:
            id: reset_connection
            widgets:
              - label:
                  id: reset_connection_label
                  align: CENTER
                  text: $mdi_restart
                  text_font: $icon_font
            on_press:
              - wifi.disable:
              - delay: 3s
              - wifi.enable:
