---
# Blind Cover button state
# vars:
#   uid: <unique identifer for the switch. Must match the ID of the button>
#   entity_id: <Home Assistant entity_id for the object we are controlling>
sensor:
  - id: cover_${uid}_position
    platform: homeassistant
    entity_id: ${entity_id}
    attribute: current_position
    on_value:
      - lvgl.slider.update:
          id: slider_${uid}
          value: !lambda return x;
      - lvgl.label.update:
          id: label_${uid}_pos
          text:
            format: "%.0f%%"
            args: [ 'x' ]